# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: air-format

jobs:
  air-format:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2
      - uses: n1hility/cancel-previous-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v2

      - name: Configure GH
        run: |
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Air latest
        shell: bash
        run: |
          curl -LsSf https://github.com/posit-dev/air/releases/latest/download/air-installer.sh | sh

      - name: Air version
        shell: bash
        run: |
          echo ""
          echo "Formatting R code with $(air --version)"
          echo ""

      - name: Format R code using Air
        shell: bash
        run: air format .

      - name: Commit any Air formatting changes
        shell: bash
        run: |
          # Stage any modified R files
          find . -type f \( -name '*.r' -o -name '*.R' \) -exec git add -u {} +
          
          # Check if there are any changes to commit
          if git diff --cached --quiet; then
            echo "No changes found in any R files"
          else
            echo "Staging and committing modified R files"
            git commit -m '`air format` (GitHub Actions)'
            git push
          fi