on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: air-format

jobs:
  air-format:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Air latest
        shell: bash
        run: |
          curl -LsSf https://github.com/posit-dev/air/releases/latest/download/air-installer.sh | sh

      - name: Air version
        shell: bash
        run: |
          echo ""
          echo "Formatting R code with $(air --version)"
          echo ""

      - name: Format R code using Air
        shell: bash
        run: air format .

      - name: Commit any Air formatting changes
        shell: bash
        run: |
          if find . -type f \( -name '*.r' -o -name '*.R' \) -exec git add -u {} +; then
            echo "Staged modified R files"
            git commit -a -m '`air format` (GitHub Actions)'
            git push
          else
            echo "No changes found in any R files"
          fi